networks:
  app-network:
services:
  user-service:
    image: user-service:latest
    build: 
      context: .
      args: 
        - APP_NAME=user-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://user-service:3001/health", "|", "grep", "-q", "ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    environment:
      - MONGO_DB_CONN_STR=mongodb://user:pass@mongodb/task_db
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq
      - RABBIT_MQ_NOTIFICATION_QUEUE=notification
      - LOG_LEVEL=info
      - MONGO_DB_NAME=task_db
      - PORT=3001
      - STAGE=prod

  notification-service:
    image: notification-service:latest
    build: 
      context: .
      args: 
        - APP_NAME=notification-service
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://user-service:3001/health/notification-service", "|", "grep", "-q", "ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq
      - RABBIT_MQ_NOTIFICATION_QUEUE=notification
      - LOG_LEVEL=info
      - STAGE=prod

  mongodb:
    image: mongodb/mongodb-community-server
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=task_db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./db_data:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

volumes:
  db_data:
  rabbitmq_data:
  rabbitmq_log:
